{
 "title": "Flask-App",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "3s",
 "panels": [
  {
   "title": "Total deployment replicas (min 3)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kube_deployment_status_replicas{deployment=\"flask-crud-app\"}",
     "legendFormat": "{{ deployment }}"
    }
   ]
  },
  {
   "title": "Total successful requests to app.",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 0 },
   "targets": [
    {
     "expr": "sum(flask_http_request_total{method=\"GET\",status=\"200\"})",
     "legendFormat": "flask-crud-app"
    }
   ]
  },
  {
   "title": "Total successful requests by pod.",
   "type": "stat",
   "gridPos": { "h": 6, "w": 9, "x": 13, "y": 0 },
   "targets": [
    {
     "expr": "flask_http_request_total{method=\"GET\",status=\"200\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Total number requests to add a phone.",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(by_path_counter_total{path=\"/add/\"})"
    }
   ]
  },
  {
   "title": "Total phone records added.",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(by_path_counter_total{path=\"/addphone\"})"
    }
   ]
  },
  {
   "title": "Total phone records deleted.",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 6 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(by_path_counter_total{path=\"/deletephone\"})"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "graph",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(flask_http_request_total{app=\"flask-crud-app\"}[2m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{app=\"flask-crud-app\"}[2m])",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Memory usage by Pod",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app=\"flask-crud-app\"}",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{app=\"flask-crud-app\",status=\"200\"}[2m])\n/\nrate(flask_http_request_duration_seconds_count{app=\"flask-crud-app\",status=\"200\"}[2m])",
     "legendFormat": "{{ path }}"
    }
   ]
  }
 ]
}